# Hyprtoolkit theme config

font_family = JetBrains Mono Nerd Font
font_size = 11

background = rgba(191724ff)
text = rgba(e0def4ff)
accent = rgba(26233aff)
alternate_base = rgba(1e1e2eff)
rounding_large = 8
rounding_small = 5
