general {
    lock_cmd = loginctl lock-session
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpset auto
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
    on-resume = hyprctl dispatch dpms on
}